# 
# This file is auto-generated. Use the tool at ../tools/errors.h.py to regenerate.
# 

from .exceptions import *

ERROR_CODE_MAPPING = {
	M3U8AttributeError: [
		-1,
		-2,
		-3,
		-4,
		-5,
		-6,
		-7,
		-8,
		-9,
		-10,
		-11,
		-12,
		-13,
		-14,
		-15,
		-16,
		-17,
		-18,
		-19
	],
	MemoryError: [
		-20,
		-93
	],
	CallbackError: [
		-21
	],
	CLIError: [
		-22,
		-23,
		-24,
		-25,
		-26,
		-27,
		-28,
		-29,
		-30,
		-31,
		-32,
		-33,
		-34,
		-35,
		-36,
		-37,
		-38,
		-39,
		-40,
		-41,
		-42,
		-43,
		-44,
		-45
	],
	cURLError: [
		-46,
		-47,
		-48,
		-49,
		-50,
		-51,
		-52,
		-53,
		-54,
		-55,
		-56,
		-57,
		-58,
		-59,
		-60,
		-61
	],
	DownloadError: [
		-62,
		-63,
		-64
	],
	FilesystemError: [
		-65,
		-68,
		-69,
		-70,
		-71,
		-72,
		-73,
		-74,
		-75
	],
	FFmpegError: [
		-66,
		-67
	],
	M3U8ItemError: [
		-76,
		-77,
		-78,
		-79,
		-80,
		-81,
		-82,
		-83,
		-84,
		-85
	],
	UnsupportedURIError: [
		-86
	],
	M3U8MediaError: [
		-87,
		-88,
		-89,
		-90,
		-91,
		-92
	],
	M3U8ParserError: [
		-94,
		-95,
		-96,
		-97,
		-98,
		-99,
		-100,
		-101,
		-102,
		-103
	],
	M3U8PlaylistError: [
		-104,
		-105,
		-106,
		-107,
		-108,
		-109,
		-110,
		-111,
		-112
	],
	PrintfError: [
		-113
	],
	M3U8TagError: [
		-114,
		-115,
		-116,
		-117,
		-118,
		-119,
		-120
	]
}

ERROR_MESSAGE_MAPPING = {
	-1: "There must not be multiple attributes with the same name within the same tag",
	-2: "An M3U8 tag must not contain empty attributes",
	-3: "The value of this M3U8 attribute is not a valid byte range",
	-4: "The value of this M3U8 attribute is not a valid ISO/IEC 8601:2004 date/time representation",
	-5: "The value of this M3U8 attribute is not a valid enumerated string",
	-6: "The value of this M3U8 attribute is not a valid signed decimal floating point number",
	-7: "The value of this M3U8 attribute is not a valid hexadecimal sequence",
	-8: "The name of this M3U8 attribute is invalid or was not recognized",
	-9: "The value of this M3U8 attribute is not a valid quoted string",
	-10: "The value of this M3U8 attribute is not a valid decimal resolution",
	-11: "The value of this M3U8 attribute is not a valid decimal floating point number",
	-12: "The value of this M3U8 attribute is not a valid decimal integer",
	-13: "The value of this M3U8 attribute is not a valid KEYFORMATVERSIONS",
	-14: "This M3U8 tag is missing a required M3U8 attribute",
	-15: "An M3U8 attribute requires a key to be supplied",
	-16: "An M3U8 attribute requires a value to be supplied",
	-17: "Got an unexpected M3U8 attribute within this M3U8 tag",
	-18: "The value of this M3U8 attribute is invalid or was not recognized",
	-19: "The END-DATE attribute value do not match the value of the DURATION attribute value",
	-20: "Writing data to that memory address would cause a buffer overflow",
	-21: "Callback returned error",
	-22: "Got an empty argument while parsing the command-line arguments",
	-23: "This argument is invalid or was not recognized",
	-24: "This keyword argument require a value to be supplied",
	-25: "Could not guess output file format; either the codec is not supported or the media file is corrupt",
	-26: "The value specified for the keyword argument -c/--concurrency is out of range",
	-27: "This argument cannot be specified multiple times",
	-28: "The value specified for the keyword argument --max-redirs is out of range",
	-29: "No streams selected",
	-30: "No output file specified",
	-31: "The output filename does not contain a file extension",
	-32: "You are not supposed to run this program as a privileged user. Sorry.",
	-33: "The value specified for the keyword argument -r/--retry is out of range",
	-34: "Reached the maximum number of allowed media selection",
	-35: "Could not find any media stream matching the requested index",
	-36: "The value specified for the keyword argument --select-media is out of range",
	-37: "Reached the maximum number of allowed stream selection",
	-38: "This playlist does not contain any Variant Stream",
	-39: "Could not find any Variant Stream matching the requested resolution or position",
	-40: "The value specified for the keyword argument --select-stream is out of range",
	-41: "The value specified for the keyword argument --select-stream is not a valid resolution or position",
	-42: "The keyword argument --select-stream does not support wildcard matching",
	-43: "No URI specified",
	-44: "User interrupted",
	-45: "Got an unexpected value while parsing the command-line arguments",
	-46: "Could not get information about the cURL handler",
	-47: "Could not add the cURL handler to cURL multi",
	-48: "Could not initialize the cURL multi interface",
	-49: "Could not perform on cURL multi",
	-50: "Could not poll on cURL multi",
	-51: "Could not remove the cURL handler from cURL multi",
	-52: "Could not set options on cURL multi",
	-53: "Could not initialize the cURL Share interface",
	-54: "Could not set options on Share HTTP client",
	-55: "Could not initialize the cURL URL interface",
	-56: "Could not get URL from this cURL URL interface",
	-57: "Could not set URL for this cURL URL interface",
	-58: "Could not initialize the HTTP client due to an unexpected error",
	-59: "HTTP request failure",
	-60: "Could not set options on HTTP client",
	-61: "Could not append item to list",
	-62: "Could not create the temporary directory",
	-63: "Could not move file to specified location",
	-64: "Could not find a suitable directory for storing temporary files",
	-65: "Could not resolve filename",
	-66: "Could locate the FFmpeg executable",
	-67: "Could not mux media streams",
	-68: "Could not lock file",
	-69: "Could not open file",
	-70: "Tried to read contents from an empty file",
	-71: "Could not read data from file",
	-72: "Could not seek file",
	-73: "Could not get current file position",
	-74: "Could not write data to file",
	-75: "Could not get app filename",
	-76: "This M3U8 tag must not contain empty items",
	-77: "The value of this M3U8 item is not a valid byte range",
	-78: "The value of this M3U8 item is not a valid ISO/IEC 8601:2004 date/time representation",
	-79: "The value of this M3U8 item is not a valid enumerated string",
	-80: "The value of this M3U8 attribute is not a valid decimal floating point number",
	-81: "The value of this M3U8 attribute is not a valid decimal integer",
	-82: "The value of this M3U8 item is not a valid unquoted string",
	-83: "This M3U8 tag is missing a required M3U8 item",
	-84: "The value of this M3U8 item is invalid or was not recognized",
	-85: "The value of this M3U8 item is too long",
	-86: "Could not load M3U8 playlist from this URI; either this protocol is not supported or it was not recognized",
	-87: "Could not find any audio stream matching this variant stream",
	-88: "Could not find any closed-captions stream matching this variant stream",
	-89: "Could not find any subtitle stream matching this variant stream",
	-90: "Could not find any video stream matching this variant stream",
	-91: "This M3U8 playlist has no media segments",
	-92: "This Variant Stream must not have a CLOSED-CAPTIONS attribute whose value is anything other than NONE",
	-93: "Could not allocate memory",
	-94: "Could not parse this string as a byte range",
	-95: "Could not parse this string as an ISO/IEC 8601:2004 date/time representation",
	-96: "Could not parse this string as an enumerated string",
	-97: "Could not parse this string as a signed decimal floating point number",
	-98: "Could not parse this string as an hexadecimal sequence",
	-99: "Could not parse this string as a quoted string",
	-100: "Could not parse this string as a decimal resolution",
	-101: "Could not parse this string as a decimal floating point number",
	-102: "Could not parse this string as a decimal integer",
	-103: "Could not parse this string as an unquoted string",
	-104: "This M3U8 playlist contains a line that is too long",
	-105: "This M3U8 playlist contains a line that was not terminated",
	-106: "This M3U8 playlist is missing a required M3U8 tag",
	-107: "This M3U8 playlist exceeds the maximum allowed size",
	-108: "Encountered an unexpected item on the first line of the playlist",
	-109: "Encountered an unexpected playlist tag",
	-110: "This M3U8 tag does not expect any URI to be supplied, but a URI was encountered",
	-111: "Could not determine the type of this M3U8 playlist",
	-112: "This M3U8 playlist contains a M3U8 tag that is not in the expected position",
	-113: "Could not format string using snprintf",
	-114: "This M3U8 tag cannot be specified multiple times in the same playlist",
	-115: "This M3U8 tag requires a list of attributes to be supplied",
	-116: "This M3U8 tag requires a list of items to be supplied",
	-117: "This M3U8 tag requires a single-value option to be supplied",
	-118: "The name of this M3U8 tag is invalid or was not recognized",
	-119: "The attributes of this M3U8 tag do not match those of the other M3U8 tag with the same ID",
	-120: "This M3U8 tag does not require any value to be supplied, but trailing options were found"
}
